### ISSUE TITLE
Failed to execute 'uniform4fv'

### ISSUE THREAD

**Issue by benoitbohnke** [nonphoto/marbled-paper#1]
Hello, 
I'm trying to run your project but got an error `Uncaught TypeError: Failed to execute 'uniform4fv' on 'WebGLRenderingContext': Overload resolution failed.`
Do you have an idea on how I could solve this ?

Many thanks !

**Comment by nonphoto** [comment]
Hi! This project is very old and I don't have the capacity to debug this. I suspect that the error is coming from one of the [stack.gl](https://stack.gl) dependencies like `gl-shader` so you might want to try looking there. Good luck!

**Comment by benoitbohnke** [comment]
I'll check that, thanks!
